# Generated by Django 5.1.2 on 2024-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkA", models.CharField(max_length=500)),
                ("linkB", models.CharField(max_length=10)),
            ],
        ),
    ]
