# Generated by Django 4.1.6 on 2024-11-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GO", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
