# Generated by Django 4.1.6 on 2024-11-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GO", "0002_alter_class_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="counter",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.RenameModel(old_name="Class", new_name="Link",),
    ]
